### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by robwolff3** [nielsrowinbik/ha-nadtcp#2]
Hey im getting this error on Home Assistant startup with this integration. Anyone else getting this?

```
Logger: homeassistant
Source: custom_components/nadtcp2/media_player.py:217
Integration: nadtcp2 ([documentation](https://github.com/mindigmarton/ha-nadtcp))
First occurred: 11:22:12 PM (1 occurrences)
Last logged: 11:22:12 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/nadtcp2/media_player.py", line 217, in connect
    await self._client.connect()
  File "/usr/local/lib/python3.10/site-packages/nadtcp/__init__.py", line 207, in connect
    await asyncio.wait_for(
TypeError: wait_for() got an unexpected keyword argument 'loop'
```

**Comment by nielsrowinbik** [comment]
Completely missed this issue @robwolff3, but should be fixed in more recent versions.
